### ISSUE TITLE
broken icons and no blur on web discord (stylus)

### ISSUE THREAD

**Issue by czarhex** [SlippingGittys-Discord-Themes/surCord#21]
bootstrap icons don't get used, instead the icons in (/src/fixations/_assets.scss)  
look zoomed in (changing the scale doesn't fix it)

<h6>broken icons (user.css unchanged)</h6>
<img src="https://user-images.githubusercontent.com/76652465/181237147-08fa9f1e-d996-4ffd-9bfc-eaf696748c10.png" width="500">

<h6>after copying source.css and removing icons from _assets.scss (discord default icons)</h6>
<img src="https://user-images.githubusercontent.com/76652465/181237157-adb3cf2a-e0e8-4124-805b-ab23d5ea83cd.png" width="500">

my suggestions:
* build a seperate source.css for surCord.user.css without _assets.scss
* same thing but use different icons for user.css
* cook up a better idea than me :shrug: lol

icons in settings do work properly.

**Comment by SlippingGitty** [comment]
Thanks for taking the time to do a lil debugging for me.

I can get this theme running perfectly fine with Google Chrome (stable), both blur and custom SVGs. I have also asked a few friends to test this for me on Chrome, and the theme seems to be working out swimmingly for them.
![Screen Shot 2022-07-27 at 12 40 54 PM](https://user-images.githubusercontent.com/76500838/181319911-16461144-bd8c-4ebb-8eea-88ccb68b4596.png)

Attempting to use this theme on FireFox (stable) results in nothing but the font changing; everything else is untouched **_but_** the font when using the theme with Firefox.
![screendick](https://user-images.githubusercontent.com/76500838/181331534-3b81aa42-ee14-452d-acfa-5e1603d15a91.png)

> my suggestions:
> 
> * build a separate source.css for surCord.user.css without _assets.scss
> * same thing but use different icons for user.css
> * cook up a better idea than me 🤷 lol

I will consider these options if necessary, thank you. <3
___
One question that I have, hopefully it's fruitful. 

May I ask what browser you are using? My assumption is that you are using FireFox (or some derivative) based on your screenshot, but that still begs the question as to how the theme is loading on your end.

**Comment by czarhex** [comment]
I use Firefox ESR 91, was able to load the theme only after enabling the setting "Patch CSP to allow style assets"

kinda sucks it's one of those "different for chrome and firefox" situations

**Comment by czarhex** [comment]
figured out why blur isn't working on firefox-ESR, apparently firefox doesn't support backdrop-filter by default until ver. 102+
current ESR is still on ver. 91, lol

I will do more testing and research (this might need to be documented later)

**Comment by czarhex** [comment]
just tested it out on Firefox ver. 103 and both blur and icons work properly on there so problem solved, i'll make a PR later
