### ISSUE TITLE
[QUESTION] Codeblock fonts

### ISSUE THREAD

**Issue by kernel-dev** [SlippingGittys-Discord-Themes/surCord#25]
Is it possible to use SF Mono for codeblocks? If not, shouldn't the theme leave these to use their default?

**Comment by SlippingGitty** [comment]
This is something I've been meaning to get to, and I will look into it when I have the time. Thank you for reminding me.

**Comment by kernel-dev** [comment]
I would have gladly done it myself, but I'm not that proficient in CSS, nor do I know how to find hosts of these fonts. Thank you for responding so quickly, and for all your, and the rest of the contributor's, hard work.

**Comment by SlippingGitty** [comment]
https://github.com/SlippingGittys-Discord-Themes/surCord/pull/26 

Credits to @czarhex and I assume @LeafyLuigi for being the directors of this scene, and thank you for your patience. Please tell me if you have anymore issues. 

<3
