### ISSUE TITLE
Unable to click top portion of window + options off center

### ISSUE THREAD

**Issue by Evoley** [SlippingGittys-Discord-Themes/surCord#38]
Hi, I have been having this issue ever since I installed the theme where I am unable to click the top portion of the window. I also noticed that some things are also off center. 

![Discord_eQbVMaV8C8](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/10457130/86e8514a-2bf2-4bb4-8f14-f73c36857f7c)

**Comment by SlippingGitty** [comment]
Can I ask which OS you are on? The title bar is known to have some issues on Windows, which is something I don't have access to debug at the moment as a non-Windows user.

**Comment by Evoley** [comment]
I'm on Windows 11.

**Comment by SlippingGitty** [comment]
If someone is willing to fix these issues on their own time, I will gladly merge them. If my situation changes and I can have access to a Windows device, I will fix them myself. 

The issue lays entirely on how the title bar is changed with https://github.com/discord-extensions/macos-titlebar. While I would not say this is a problem that is their fault (please do not harass them, macos-title bar is a wonderful combination of efforts), this is something that could probably be easily fixed if one poured a bit of time into it.

**Comment by tilsgee** [comment]
> If someone is willing to fix these issues on their own time, I will gladly merge them. If my situation changes and I can have access to a Windows device, I will fix them myself.
> 
> The issue lays entirely on how the title bar is changed with https://github.com/discord-extensions/macos-titlebar. While I would not say this is a problem that is their fault (please do not harass them, macos-title bar is a wonderful combination of efforts), this is something that could probably be easily fixed if one poured a bit of time into it.

dude... pararells exist. or use proxmox

**Comment by SlippingGitty** [comment]
You want me to spin an entire VM for one single use case, which is to fix a Discord theme that I pour effort into on my spare time?

**Comment by tilsgee** [comment]
> You want me to spin an entire VM for one single use case, which is to fix a Discord theme that I pour effort into on my spare time?

nah. i can be your beta tester if you want.

**Comment by SlippingGitty** [comment]
That's very kind of you. I will let you know if I need any help in the future.

**Comment by Exonymos** [comment]
Are there any updates on this issue? still no fix
btw great theme been using it for some time now

**Comment by LuckFire** [comment]
> The issue lays entirely on how the title bar is changed with https://github.com/discord-extensions/macos-titlebar.

As stated, this is an issue with macos-titlebar. I have pushed a fix out for issues relating to this.
