### ISSUE TITLE
Changing accents and themes causes the theme to break

### ISSUE THREAD

**Issue by Valkarin1029** [SlippingGittys-Discord-Themes/surCord#40]
# With it set to default
![image=512](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/49566256/99b386d8-b620-4174-a479-f89545b76d4c)
![image=512](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/49566256/0fd95e1d-ef00-4bee-8b70-2cb7f13acbdb)
# With Tokyo Accent
![image=512](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/49566256/051009b7-d35a-4f18-a875-1264eac06f39)
![image=512x512](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/49566256/665860d5-0784-4d1d-8cdf-d8a400c9b56c)
# With Tokyo Night Pallete
![image](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/49566256/c6c1f743-d71b-432f-b4a5-fcd8bc2d274d)
![image](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/49566256/b6535dae-c833-4f95-820c-8fab39dc97bb)

**Comment by SlippingGitty** [comment]
^
