### ISSUE TITLE
Suggestions: You CAN actually enable transparency on windows 10 or 11, by using Mica For Everyone

### ISSUE THREAD

**Issue by tilsgee** [SlippingGittys-Discord-Themes/surCord#42]
the Readme says "for macOS only", that's not true.
although, when enabled, it looks little janky compared when using other "translucent" theme.

![gambar](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/62179071/0da6d412-0011-4be6-bd1f-c7816e9da176)

**Comment by tilsgee** [comment]
really, bro?.

the bug isn't in theme itself, calm down xD

it's in "Mica for Everyone" itself

here's how it look normally

![gambar](https://github.com/SlippingGittys-Discord-Themes/surCord/assets/62179071/30679791-ef64-4159-b59e-71387536624b)

**Comment by SlippingGitty** [comment]
I will not be removing it from the readme. "only on macOS" is there to signify that I only plan on fixing or maintaining the transparency addon for the theme on macOS for the time being.
