### ISSUE TITLE
[SlidetoUnlock] Theme won't work

### ISSUE THREAD

**Issue by xxHAKRxx** [SlippingGittys-Discord-Themes/surCord#54]
I know this has nothing to do with SurCord, but you haven't responded to a similar issue brought up back in June so I assume you're not active there, which I why I've decided to bring it up here.
![image](https://github.com/user-attachments/assets/27ca1c12-b6fc-4ab3-b88c-c685aac52d2e)
Like the comment above says, the theme literally doesn't work. All it does is change the font and nothing else (pic below for proof).
![image](https://github.com/user-attachments/assets/58cb2574-7efa-41e7-a256-e81e8f5c21a0)
I know you probably don't update the theme anymore, but could you please make it actually work? The theme looks so good from the screenshots and it's such a shame that people won't get to experience it because the theme won't work.

**Comment by SlippingGitty** [comment]
please dont make unrelated issues here. if i didnt respond in the other repo, it means i was busy, or didnt wanna get to it at the moment. moving your issue to another repo wont make me wanna do it more, just begrudgingly-- which has been done.
